### ISSUE TITLE
bool isFlippedPole

### ISSUE THREAD

**Issue by RiverIntheSky** [Grillnov/KaminoGPU#2]
can you explain why the variable `isFlippedPole` only in function `sampleVPhi()` of type `fReal` is, 
https://github.com/Grillnov/KaminoGPU/blob/4f8c682084d5772aa593155df1a6dde3b92331db/KaminoGPU/kernel/KaminoCore.cu#L43
and everywhere else `bool`? 
https://github.com/Grillnov/KaminoGPU/blob/4f8c682084d5772aa593155df1a6dde3b92331db/KaminoGPU/kernel/KaminoCore.cu#L93
https://github.com/Grillnov/KaminoGPU/blob/4f8c682084d5772aa593155df1a6dde3b92331db/KaminoGPU/kernel/KaminoCore.cu#L143
What about the comprison of `bool` with a `float` type `-1.0f`?
https://github.com/Grillnov/KaminoGPU/blob/4f8c682084d5772aa593155df1a6dde3b92331db/KaminoGPU/kernel/KaminoCore.cu#L152

**Comment by Uchanka** [comment]
Fixed. It should be a bug.

Thanks for pointing out.
